kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jaime-agents-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: ocs-storagecluster-cephfs
  volumeMode: Filesystem
