####################################################
# SECRETS
####################################################

apiVersion: v1
kind: Secret
metadata:
  name: credentials-jaime
  namespace: jaime
type: Opaque 
data: 
  JAIME_USER: YWRtaW4=
  JAIME_PASS: YWRtaW4=

---

apiVersion: v1
kind: Secret
metadata:
  name: credentials-postgres
  namespace: jaime
type: Opaque 
data: 
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=

---

####################################################
# SERVICES
####################################################

apiVersion: v1
kind: Service
metadata:
  name: jaime-back
  namespace: jaime
  labels:
    application: jaime
    component: server
spec:
  selector:
    app: jaime-back
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: jaime-front
  namespace: jaime
  labels:
    application: jaime
    component: frontend
spec:
  selector:
    app: jaime-front
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: jaime
  labels:
    application: jaime
    component: db
spec:
  ports:
  - port: 5432
    protocol: TCP
  selector:
    app: postgres

---

####################################################
# ROUTES
####################################################

kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: jaime-front
  namespace: jaime
  labels:
    application: jaime
    component: frontend
spec:
  to:
    name: jaime-front
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None

---

kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: jaime-back
  namespace: jaime
  labels:
    application: jaime
    component: server
spec:
  to:
    name: jaime-back
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None

---

kind: Route
apiVersion: route.openshift.io/v1
id: jaime-pushgateway
metadata:
  name: jaime-pushgateway
  namespace: jaime
  labels:
    application: jaime
    component: agent
spec:
  to:
    name: jaime-agent-pushgateway
  port:
    targetPort: pushgateway
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None

---

####################################################
# DEPLOYMENTS
####################################################

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    application: jaime
    component: server
  name: jaime-back
  namespace: jaime
spec:
  selector:
    matchLabels:
      app: jaime-back
  replicas: 1
  template:
    metadata:
      labels:
        app: jaime-back
    spec:
      volumes:
        - name: jaime-pvc
          persistentVolumeClaim:
            claimName: jaime-pvc
      containers:
        - name: jaime
          image: 'ghcr.io/jaime-project/jaime-back:0.5.0'
          securityContext:
            runAsNonRoot: true
          env:
            - name: DB_URL
              value: postgresql+pg8000://postgres:postgres@postgres:5432/jaime
          envFrom:
            - secretRef:
                name: credentials-jaime
          ports:
            - containerPort: 5000
              protocol: TCP
          volumeMounts:
            - name: jaime-pvc
              mountPath: /home/jaime/
      

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    application: jaime
    component: frontend
  name: jaime-front
  namespace: jaime
spec:
  selector:
    matchLabels:
      app: jaime-front
  replicas: 1
  template:
    metadata:
      labels:
        app: jaime-front
    spec:
      containers:
        - name: jaime
          image: 'ghcr.io/jaime-project/jaime-front:0.5.0'
          securityContext:
            runAsNonRoot: true
          env:
            - name: JAIME_URL
              value: https://<jaime-route-url>/
          ports:
            - containerPort: 8080
          protocol: TCP
      

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    application: jaime
    component: db
  name: postgres
  namespace: jaime
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
        - name: postgres-pvc
          persistentVolumeClaim:
            claimName: postgres-pvc
      containers:
        - name: postgres
          image: docker.io/library/postgres:15
          env:
            - name: POSTGRES_DB
              value: jaime
          envFrom:
            - secretRef:
                name: credentials-postgres
          ports:
            - containerPort: 5432
              protocol: UDP
          volumeMounts:
            - name: postgres-pvc
              mountPath: /var/lib/postgresql
      
---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    application: jaime
    component: agent
  name: jaime-agent
  namespace: jaime
spec:
  selector:
    matchLabels:
      app: jaime-agent
  replicas: 1
  template:
    metadata:
      labels:
        app: jaime-agent
    spec:
      volumes:
        - name: jaime-pvc
          persistentVolumeClaim:
            claimName: jaime-pvc
      containers:
        - name: jaime
          image: 'ghcr.io/jaime-project/jaime-agent:0.5.0'
          securityContext:
            runAsNonRoot: true
          env:
            - name: JAIME_URL
              value: http://jaime-back:5000/
          ports:
            - containerPort: 7001
              protocol: TCP
          volumeMounts:
            - name: jaime-pvc
              mountPath: /home/jaime/

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    application: jaime
    component: agent
  name: jaime-agent-cluster
  namespace: jaime
spec:
  selector:
    matchLabels:
      app: jaime-agent-cluster
  replicas: 1
  template:
    metadata:
      labels:
        app: jaime-agent-cluster
    spec:
      volumes:
        - name: jaime-pvc
          persistentVolumeClaim:
            claimName: jaime-pvc
      containers:
        - name: jaime
          image: 'ghcr.io/jaime-project/jaime-agent-cluster:0.5.0'
          securityContext:
            runAsNonRoot: true
          env:
            - name: JAIME_URL
              value: http://jaime-back:5000/
          ports:
            - containerPort: 7001
              protocol: TCP
          volumeMounts:
            - name: jaime-pvc
              mountPath: /home/jaime/

---

####################################################
# PVCs
####################################################

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jaime-pvc
  namespace: jaime
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pvc
  namespace: jaime
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem

---
