version: "3.8"

services:

    postgres:
        image: docker.io/library/postgres:15.1
        container_name: postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=jaime
        volumes:
            - postgres:/var/lib/postgresql/data:rw
        network_mode: host

    jaime-back:
        container_name: jaime-back
        image: ghcr.io/jaime-project/jaime-back:1.12.0
        environment:
            - DB_URL=postgresql+pg8000://postgres:postgres@localhost:5432/jaime
            - JAIME_USER=admin
            - JAIME_PASS=admin
            - PYTHON_PORT=5000
        volumes:
            - jaime:/jaime:rw
            - shared:/shared:rw
        network_mode: host
        depends_on:
            - postgres

    jaime-front:
        container_name: jaime-front
        image: ghcr.io/jaime-project/jaime-front:1.12.0
        environment:
            - JAIME_URL=http://localhost:5000
        network_mode: host

    agent1:
        container_name: agent1
        image: ghcr.io/jaime-project/jaime-agent:1.12.0
        environment:
            - JAIME_URL=http://localhost:5000
            - PYTHON_PORT=7001
        volumes:
            - shared:/shared
        network_mode: host
        depends_on:
            - jaime-back

    agent2:
        container_name: agent2
        image: ghcr.io/jaime-project/jaime-agent-kubernetes:1.12.0
        environment:
            - JAIME_URL=http://localhost:5000
            - PYTHON_PORT=7002
        volumes:
            - shared:/shared
        network_mode: host
        depends_on:
            - jaime-back

    agent3:
        container_name: agent3
        image: ghcr.io/jaime-project/jaime-agent-openshift:1.12.0
        environment:
            - JAIME_URL=http://localhost:5000
            - PYTHON_PORT=7003
        volumes:
            - shared:/shared
        network_mode: host
        depends_on:
            - jaime-back

    agent4:
        container_name: agent4
        image: ghcr.io/jaime-project/jaime-agent-pushgateway:1.12.0
        environment:
            - JAIME_URL=http://localhost:5000
            - PYTHON_PORT=7004
        volumes:
            - shared:/shared
        network_mode: host
        depends_on:
            - jaime-back

volumes:
    jaime:
        external: false
    shared:
        external: false
    postgres:
        external: false
