version: "3.8"

services:

    ####################################################
    # JAIME
    ####################################################

    jaime:
        container_name: jaime
        image: brianwolf94/jaime:1.5.0
        volumes:
            - jaime:/root/.jaime
            - shared:/data
        ports:
            - 5000:5000

    agent1:
        container_name: jaime-agent1
        image: brianwolf94/jaime-agent:1.5.0
        environment:
            - JAIME_URL=http://jaime:5000
        volumes:
            - shared:/data
        ports:
            - 7001:7001

    agent2:
        container_name: jaime-agent2
        image: brianwolf94/jaime-agent-kubernetes:1.5.0
        environment:
            - JAIME_URL=http://jaime:5000
        volumes:
            - shared:/data
        ports:
            - 7002:7001

    agent3:
        container_name: jaime-agent3
        image: brianwolf94/jaime-agent-openshift:1.5.0
        environment:
            - JAIME_URL=http://jaime:5000
        volumes:
            - shared:/data
        ports:
            - 7003:7001

    front:
        container_name: jaime-front
        image: brianwolf94/jaime-front:1.5.0
        environment:
            - JAIME_URL=http://0.0.0.0:5000
        ports:
            - 4200:80

    ####################################################
    # TOOLS
    ####################################################

    dozzle:
        container_name: dozzle
        image: amir20/dozzle
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - 8081:8080

    filebrowser:
        container_name: filebrowser
        image: hurlenko/filebrowser
        volumes:
            - shared:/data:rw
            - shared:/config:rw
        ports:
            - 8080:8080

volumes:
    jaime:
        external: false
    shared:
        external: false

networks:
  default:
    external:
      name: jaime-net
