apiVersion: template.openshift.io/v1
kind: Template
labels:
  jaime: 1.7.0
  template: jaime
message: 'Una desc'
metadata:
  annotations:
    description: An example application.
    iconClass: icon-sso
    openshift.io/display-name: Jaime  Project by Braian Lobo and Pablo Castelo
    tags: jaime,openshift,automation
    version: 1.7.0
  name: jaime
objects:

####################################################
# SERVICES
####################################################

- apiVersion: v1
  kind: Service
  metadata:
    name: jaime
    labels:
      application: jaime
      component: server
  spec:
    selector:
      app: jaime
    ports:
    - protocol: TCP
      port: 5000
      name: jaimebe
      targetPort: 5000

- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: The web server's port.
    labels:
      application: jaime-front
      component: frontend  
    name: jaime-front
  spec:
    selector:
      app: jaime-front
    ports:
      - protocol: TCP
        port: 80
        name: front
        targetPort: 8080

- apiVersion: v1
  kind: Service
  metadata:
    name: jaime-agent-pushgateway
    labels:
      application: jaime-agent-pushgateway
      component: agent 
  spec:
    ports:
    - port: 7001
      protocol: TCP
      name: agent
    - port: 9091
      protocol: TCP
      name: pushgateway
    selector:
      app: jaime-agent-pushgateway     

- apiVersion: v1
  kind: Service
  metadata:
    name: jaime-agent-base
    labels:
      application: jaime-agent-base
      component: agent 
  spec:
    ports:
    - port: 7001
      name: agent
    selector:
      app: jaime-agent-base

- apiVersion: v1
  kind: Service
  metadata:
    name: jaime-agent-kubernetes
    labels:
      application: jaime-agent-kubernetes
      component: agent 
  spec:
    ports:
    - port: 7001
      name: agent
    selector:
      app: jaime-agent-kubernetes

- apiVersion: v1
  kind: Service
  metadata:
    name:  jaime-agent-openshift
    labels:
      application: jaime-agent-openshift
      component: agent 
  spec:
    ports:
    - port: 7001
      name: agent
    selector:
      app:  jaime-agent-openshift

####################################################
# ROUTES      
####################################################

- kind: Route
  apiVersion: route.openshift.io/v1
  id: jaime-front-http
  metadata:
    annotations:
      description: Route for frontend's http service.
    labels:
      application: jaime
      component: frontend
    name: jaime-front
  spec:
    host: jaime-front-${NAMESPACE}.${CLUSTER_WILDCARD}
    to:
      name: jaime-front

- kind: Route
  apiVersion: route.openshift.io/v1
  id: jaime-http
  metadata:
    annotations:
      description: Route for application's http service.
    labels:
      application: jaime
      component: server
    name: jaime
  spec:
    host: jaime-${NAMESPACE}.${CLUSTER_WILDCARD}
    to:
      name: jaime
      
- kind: Route
  apiVersion: route.openshift.io/v1
  id: jaime-pushgateway
  metadata:
    annotations:
      description: Route for pushgateway server.
    labels:
      application: jaime-pushgateway
      component: server
    name: jaime-pushgateway
  spec:
    to:
      name: jaime-agent-pushgateway
    port:
      targetPort: pushgateway  

####################################################
# DEPLOYMENTS
####################################################

- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      application: jaime
      component: server
    name: jaime
  spec:
    selector:
      matchLabels:
        app: jaime
    replicas: 1
    strategy:
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: jaime
      spec:
        volumes:
          - name: jaime-pvc
            persistentVolumeClaim:
              claimName: jaime-pvc
          - name: jaime-agents-pvc
            persistentVolumeClaim:
              claimName: jaime-agents-pvc
        containers:
          - name: jaime
            image: 'ghcr.io/jaime-project/jaime:${JAIME_VERSION}'
            ports:
              - containerPort: 5000
                protocol: TCP
            volumeMounts:
              - name: jaime-pvc
                mountPath: /home/jaime/.jaime
              - name: jaime-agents-pvc
                mountPath: /data
        restartPolicy: Always  

- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      application: jaime-front
      component: frontend
    name: jaime-front
  spec:
    selector:
      matchLabels:
        app: jaime-front
    replicas: 1
    strategy:
      type: RollingUpdate    
    template:
      metadata:
        labels:
          app: jaime-front
      spec:
        containers:
          - name: jaime-front
            image: 'ghcr.io/jaime-project/jaime-front:${JAIME_VERSION}'
            env:
              - name: JAIME_URL
                value: http://jaime-${NAMESPACE}.${CLUSTER_WILDCARD}
            ports:
              - containerPort: 8080
                protocol: TCP
        restartPolicy: Always 

####################################################
# STATEFULSETS      
####################################################

- kind: StatefulSet
  apiVersion: apps/v1
  metadata:
    labels:
      application: jaime-agent-openshift
      component: agent  
    name: jaime-agent-openshift
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: jaime-agent-openshift
    template:
      metadata:
        labels:
          app: jaime-agent-openshift
      spec:
        volumes:
          - name: jaime-agents-pvc
            persistentVolumeClaim:
              claimName: jaime-agents-pvc
        containers:
          - name: jaime-agent-openshift
            image: 'ghcr.io/jaime-project/jaime-agent-openshift:${JAIME_VERSION}'
            ports:
              - name: agent
                containerPort: 7001
                protocol: TCP
            env:
              - name: JAIME_URL
                value: http://jaime:5000
            imagePullPolicy: IfNotPresent
            volumeMounts:
              - name: jaime-agents-pvc
                mountPath: /data
        restartPolicy: Always
    serviceName: jaime-agent-openshift
    podManagementPolicy: OrderedReady
    updateStrategy:
      type: RollingUpdate

- kind: StatefulSet
  apiVersion: apps/v1
  metadata:
    labels:
      application: jaime-agent-kubernetes
      component: agent    
    name: jaime-agent-kubernetes
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: jaime-agent-kubernetes
    template:
      metadata:
        labels:
          app: jaime-agent-kubernetes
      spec:
        volumes:
          - name: jaime-agents-pvc
            persistentVolumeClaim:
              claimName: jaime-agents-pvc
        containers:
          - name: jaime-agent-kubernetes
            image: 'ghcr.io/jaime-project/jaime-agent-kubernetes:${JAIME_VERSION}'
            ports:
              - name: agent
                containerPort: 7001
                protocol: TCP
            env:
              - name: JAIME_URL
                value: http://jaime:5000
            imagePullPolicy: IfNotPresent
            volumeMounts:
              - name: jaime-agents-pvc
                mountPath: /data
        restartPolicy: Always
    serviceName: jaime-agent-kubernetes
    podManagementPolicy: OrderedReady
    updateStrategy:
      type: RollingUpdate

- kind: StatefulSet
  apiVersion: apps/v1
  metadata:
    labels:
      application: jaime-agent-base
      component: agent      
    name: jaime-agent-base
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: jaime-agent-base
    template:
      metadata:
        labels:
          app: jaime-agent-base
      spec:
        volumes:
          - name: jaime-agents-pvc
            persistentVolumeClaim:
              claimName: jaime-agents-pvc
        containers:
          - name: jaime-agent-base
            image: 'ghcr.io/jaime-project/jaime-agent:${JAIME_VERSION}'
            ports:
              - name: agent
                containerPort: 7001
                protocol: TCP
            env:
              - name: JAIME_URL
                value: http://jaime:5000
            imagePullPolicy: IfNotPresent
            volumeMounts:
              - name: jaime-agents-pvc
                mountPath: /data
        restartPolicy: Always
    serviceName: jaime-agent-base
    podManagementPolicy: OrderedReady
    updateStrategy:
      type: RollingUpdate

- kind: StatefulSet
  apiVersion: apps/v1
  metadata:
    labels:
      application: jaime-agent-pushgateway
      component: agent    
    name: jaime-agent-pushgateway
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: jaime-agent-pushgateway
    template:
      metadata:
        labels:
          app: jaime-agent-pushgateway
      spec:
        volumes:
          - name: jaime-agents-pvc
            persistentVolumeClaim:
              claimName: jaime-agents-pvc
        containers:
          - name: jaime-agent-base
            image: 'ghcr.io/jaime-project/jaime-agent-pushgateway:${JAIME_VERSION}'
            ports:
              - name: agent
                containerPort: 7001
                protocol: TCP
              - name: gateway
                containerPort: 9091
                protocol: TCP              
            env:
              - name: JAIME_URL
                value: http://jaime:5000
            imagePullPolicy: IfNotPresent
            volumeMounts:
              - name: jaime-agents-pvc
                mountPath: /data
        restartPolicy: Always
    serviceName: jaime-agent-pushgateway
    podManagementPolicy: OrderedReady
    updateStrategy:
      type: RollingUpdate
      
####################################################
# PVCs      
####################################################

- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: jaime-pvc
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: ${JAIME_VOLUME_SIZE}
    storageClassName: ocs-storagecluster-cephfs
    volumeMode: Filesystem

- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: jaime-agents-pvc
  spec:
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: ${AGENTS_VOLUME_SIZE}
    storageClassName: ocs-storagecluster-cephfs
    volumeMode: Filesystem

####################################################
# PARAMS      
####################################################

parameters:

- description: 'Version of Jaime to download images'
  name: JAIME_VERSION
  required: true  

- description: 'Cluster hostname wildcard for example: apps.cluster-r27z5.r27z5.sandbox1263.opentlc.com'
  displayName: Cluster hostname wildcard
  name: CLUSTER_WILDCARD
  required: true

- description: 'Jaime volume size'
  displayName: Jaime volume size
  name: JAIME_VOLUME_SIZE
  required: false
  value: 2Gi

- description: 'Agents volume size'
  displayName: Agents volume size
  name: AGENTS_VOLUME_SIZE
  required: false
  value: 8Gi

- description: 'Namespace to install'
  displayName: Namespace
  name: NAMESPACE
  required: false
  value: jaime
