version: "3.8"

services:

    jaime-back:
        container_name: jaime-back
        image: ghcr.io/jaime-project/jaime-back:1.10.0
        volumes:
            - jaime:/home/jaime/.jaime
            - shared:/data
        ports:
            - 5000:5000

    jaime-front:
        container_name: jaime-front
        image: ghcr.io/jaime-project/jaime-front:1.10.0
        environment:
            - JAIME_URL=http://jaime-back:5000
        ports:
            - 8080:8080

    agent1:
        container_name: agent1
        hostname: agent1
        image: ghcr.io/jaime-project/jaime-agent:1.10.0
        environment:
            - JAIME_URL=http://jaime-back:5000
        volumes:
            - shared:/data
        ports:
            - 7001:7001

    agent2:
        container_name: agent2
        hostname: agent2
        image: ghcr.io/jaime-project/jaime-agent-kubernetes:1.10.0
        environment:
            - JAIME_URL=http://jaime-back:5000
        volumes:
            - shared:/data
        ports:
            - 7002:7001

    agent3:
        container_name: agent3
        hostname: agent3
        image: ghcr.io/jaime-project/jaime-agent-openshift:1.10.0
        environment:
            - JAIME_URL=http://jaime-back:5000
        volumes:
            - shared:/data
        ports:
            - 7003:7001

    agent4:
        container_name: agent4
        hostname: agent4
        image: ghcr.io/jaime-project/jaime-agent-pushgateway:1.10.0
        environment:
            - JAIME_URL=http://jaime-back:5000
        volumes:
            - shared:/data
        ports:
            - 7004:7001
            - 9091:9091

volumes:
    jaime:
        external: false
    shared:
        external: false

networks:
    default:
        external:
            name: jaime-net
