version: "3.8"

services:

    postgres:
        container_name: postgres
        image: docker.io/library/postgres:15.1
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: jaime
        volumes:
            - postgres:/var/lib/postgresql/data:rw
        ports:
            - 5432:5432

    jaime-back:
        container_name: jaime-back
        hostname: jaime-back
        image: ghcr.io/jaime-project/jaime-back:1.13.0
        environment:
            DB_URL: postgresql+pg8000://postgres:postgres@postgres:5432/jaime
            JAIME_USER: admin
            JAIME_PASS: admin
        volumes:
            - jaime:/home/jaime/.jaime/:rw
            - shared:/home/jaime/.shared/:rw
        ports:
            - 5000:5000
        depends_on:
            - postgres

    jaime-front:
        container_name: jaime-front
        hostname: jaime-front
        image: ghcr.io/jaime-project/jaime-front:1.13.0
        environment:
            - JAIME_URL=http://localhost:5000
        ports:
            - 8080:8080

    agent-cluster:
        container_name: agent-cluster
        hostname: agent-cluster
        image: ghcr.io/jaime-project/jaime-agent-cluster:1.13.0
        environment:
            - JAIME_URL=http://jaime-back:5000
        volumes:
            - shared:/home/jaime/.shared/:rw
        ports:
            - 7001:7001
        depends_on:
            - jaime-back

    agent-pushgateway:
        container_name: agent-pushgateway
        hostname: agent-pushgateway
        image: ghcr.io/jaime-project/jaime-agent-pushgateway:1.13.0
        environment:
            - JAIME_URL=http://jaime-back:5000
        volumes:
            - shared:/home/jaime/.shared/:rw
        ports:
            - 7002:7001
            - 9091:9091
        depends_on:
            - jaime-back

volumes:
    jaime:
        external: false
    shared:
        external: false
    postgres:
        external: false
