kind: Route
apiVersion: route.openshift.io/v1
id: jaime-pushgateway
metadata:
  annotations:
    description: Route for pushgateway server.
  labels:
    application: jaime-pushgateway
    component: server
  name: jaime-pushgateway
spec:
  to:
    name: jaime-agent-pushgateway
  port:
    targetPort: pushgateway
