services:

    jaime-postgres:
        container_name: jaime-postgres
        hostname: jaime-postgres
        image: docker.io/library/postgres:15.1
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: jaime
        volumes:
            - jaime-postgres:/var/lib/postgresql/data:rw
        expose:
            - 5432

    jaime-back:
        container_name: jaime-back
        hostname: jaime-back
        image: ghcr.io/jaime-project/jaime-back:0.5.0
        environment:
            DB_URL: postgresql+pg8000://postgres:postgres@jaime-postgres:5432/jaime
            JAIME_USER: admin
            JAIME_PASS: admin
        volumes:
            - jaime:/home/jaime/:rw
        ports:
            - 5000:5000
        depends_on:
            - jaime-postgres

    jaime-front:
        container_name: jaime-front
        hostname: jaime-front
        image: ghcr.io/jaime-project/jaime-front:0.5.0
        environment:
            - JAIME_URL=http://localhost:5000
        ports:
            - 8080:8080
        depends_on:
            - jaime-back

    agent-base:
        container_name: agent-base
        hostname: agent-base
        image: ghcr.io/jaime-project/jaime-agent:0.5.0
        environment:
            - JAIME_URL=http://jaime-back:5000
        volumes:
            - jaime:/home/jaime/:rw
        expose:
            - 7001
        depends_on:
            - jaime-back
        deploy:
            replicas: 1

    agent-cluster:
        image: ghcr.io/jaime-project/jaime-agent-cluster:0.5.0
        environment:
            - JAIME_URL=http://jaime-back:5000
        volumes:
            - jaime:/home/jaime/:rw
        expose:
            - 7001
        depends_on:
            - jaime-back
        deploy:
            replicas: 1

    agent-pushgateway:
        image: ghcr.io/jaime-project/jaime-agent-pushgateway:0.5.0
        user: "1001"
        environment:
            - JAIME_URL=http://jaime-back:5000
        volumes:
            - jaime:/home/jaime/:rw
        expose:
            - 7001
        depends_on:
            - jaime-back
        deploy:
            replicas: 1

volumes:
    jaime:
        external: false
    jaime-postgres:
        external: false
