apiVersion: v1
kind: Service
metadata:
  name: jaime-agent-base
  labels:
    application: jaime-agent-base
    component: agent
spec:
  ports:
    - port: 7001
      name: agent
  selector:
    app: jaime-agent-base
