apiVersion: v1
kind: Service
metadata:
  name: jaime-agent-pushgateway
  labels:
    application: jaime-agent-pushgateway
    component: agent
spec:
  ports:
    - port: 7001
      protocol: TCP
      name: agent
    - port: 9091
      protocol: TCP
      name: pushgateway
  selector:
    app: jaime-agent-pushgateway
