apiVersion: v1
kind: Service
metadata:
  name: jaime
  labels:
    application: jaime
    component: server
spec:
  selector:
    app: jaime
  ports:
    - protocol: TCP
      port: 5000
      name: jaimebe
      targetPort: 5000
