apiVersion: v1
kind: Service
metadata:
  annotations:
    description: The web server's port.
  labels:
    application: jaime-front
    component: frontend
  name: jaime-front
spec:
  selector:
    app: jaime-front
  ports:
    - protocol: TCP
      port: 80
      name: front
      targetPort: 8080
