apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    application: jaime
    component: server
  name: jaime
spec:
  selector:
    matchLabels:
      app: jaime
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: jaime
    spec:
      volumes:
        - name: jaime-pvc
          persistentVolumeClaim:
            claimName: jaime-pvc
        - name: jaime-agents-pvc
          persistentVolumeClaim:
            claimName: jaime-agents-pvc
      containers:
        - name: jaime
          image: 'ghcr.io/jaime-project/jaime:1.7.10'
          ports:
            - containerPort: 5000
              protocol: TCP
          volumeMounts:
            - name: jaime-pvc
              mountPath: /home/jaime/.jaime
            - name: jaime-agents-pvc
              mountPath: /data
      restartPolicy: Always
