apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    application: jaime-front
    component: frontend
  name: jaime-front
spec:
  selector:
    matchLabels:
      app: jaime-front
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: jaime-front
    spec:
      containers:
        - name: jaime-front
          image: 'ghcr.io/jaime-project/jaime-front:1.7.8'
          env:
            - name: JAIME_URL
              value: http://ChangeMe/
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always

